{% set version = "0.2.6" %}

package:
  name: universal_pathlib
  version: {{ version }}

source:
  # If getting the source from GitHub, remove the line above,
  # uncomment the line below, and modify as needed. Use releases if available:
  url: https://pypi.org/packages/source/u/universal_pathlib/universal_pathlib-{{ version }}.tar.gz
  sha256: 50817aaeaa9f4163cb1e76f5bdf84207fa05ce728b23fd779479b3462e5430ac

build:
  noarch: python
  number: 0

outputs:
  - name: universal_pathlib
    build:
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools >=48
        - setuptools-scm >=6.3.1
      run:
        - python >={{ python_min }}
        - fsspec >=2022.1.0,!=2024.3.1
    test:
      requires:
        - python {{ python_min }}
      imports:
        - upath

  - name: universal-pathlib
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('universal_pathlib', max_pin="x.x.x") }}
    test:
      imports:
        - upath

about:
  home: https://github.com/fsspec/universal_pathlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pathlib api extended to use fsspec backends
  dev_url: https://github.com/fsspec/universal_pathlib

extra:
  recipe-maintainers:
    - ap--
    - andrewfulton9
