{% set version = "0.3.2" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: universal_pathlib
  version: {{ version }}

source:
  # If getting the source from GitHub, remove the line above,
  # uncomment the line below, and modify as needed. Use releases if available:
  url: https://pypi.org/packages/source/u/universal_pathlib/universal_pathlib-{{ version }}.tar.gz
  sha256: cfec30ad6094236bb1bc55715bea7664b4591eaf4ea92ad4011a0228fd20bbe5

build:
  noarch: python
  number: 0

outputs:
  - name: universal_pathlib
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools >=64
        - setuptools-scm >=8
      run:
        - python >={{ python_min }}
        - fsspec >=2024.5.0
        - pathlib-abc ==0.5.1
    test:
      requires:
        - python {{ python_min }}
      imports:
        - upath
        - upath.types
        - upath.registry

  - name: universal-pathlib
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('universal_pathlib', max_pin="x.x.x") }}
    test:
      imports:
        - upath
        - upath.types
        - upath.registry

about:
  home: https://github.com/fsspec/universal_pathlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pathlib api extended to use fsspec backends
  dev_url: https://github.com/fsspec/universal_pathlib

extra:
  recipe-maintainers:
    - ap--
    - andrewfulton9
